// Dizionario i18n BYH — 4 lingue. Chiavi piatte, {var} per interpolazione.
export type Locale = "it" | "en" | "pt" | "es";

export const LOCALES: { code: Locale; label: string; flag: string }[] = [
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "en", label: "English", flag: "🇬🇧" },
  { code: "pt", label: "Português", flag: "🇵🇹" },
  { code: "es", label: "Español", flag: "🇪🇸" },
];

export const DEFAULT_LOCALE: Locale = "it";
export const LOCALE_COOKIE = "byh_locale";

export const dict: Record<Locale, Record<string, string>> = {
  it: {
    "nav.dashboard": "Dashboard", "nav.clients": "Clienti", "nav.workouts": "Schede", "nav.messages": "Messaggi", "nav.products": "Prodotti", "nav.earnings": "Guadagni", "nav.network": "Rete / Inviti", "nav.profile": "Profilo", "nav.myPlan": "La mia scheda", "nav.progress": "Progressi", "nav.medals": "Medagliere", "nav.shop": "Shop", "nav.catalog": "Catalogo Prodotti", "nav.users": "Utenti", "nav.trainerNetwork": "Rete Trainer", "nav.sales": "Vendite", "nav.settings": "Impostazioni", "nav.account": "Account",
    "role.trainer": "Personal Trainer", "role.client": "Cliente", "role.admin": "Admin",
    "notif.title": "Notifiche", "notif.markRead": "Segna come lette", "notif.empty": "Nessuna notifica", "notif.newMessage": "Nuovo messaggio da {name}",
    "lang.title": "Lingua",
    "dash.hi": "Ciao, {name}", "dash.today": "Oggi", "dash.dayOf": "Oggi · Giorno {n} di {total}", "dash.doneToday": "Fatto oggi", "dash.meta": "{n} esercizi · ~{min} min", "dash.moreExercises": "+ altri {n} esercizi", "dash.start": "Inizia allenamento", "dash.startAgain": "Allenati di nuovo", "dash.thisWeek": "Questa settimana", "dash.progress": "Progressi", "dash.workoutsLabel": "Allenamenti", "dash.kcalBurned": "kcal bruciate", "dash.activeTime": "tempo attivo", "dash.streak": "streak consecutiva", "dash.min": "min", "dash.days": "giorni", "dash.unread": "Non letti", "dash.currentWeight": "Peso attuale", "dash.shopSub": "Consigli BYH", "dash.yourTrainer": "Il tuo trainer", "dash.writeTrainer": "Scrivi al trainer", "dash.recommended": "Consigliati dal trainer", "dash.noPlan": "Nessuna scheda attiva", "dash.noPlanSub": "Il tuo trainer ti assegnerà presto un programma.", "dash.waiting": "In attesa del tuo trainer", "dash.waitingSub": "Il tuo profilo verrà attivato quando un trainer ti aggiungerà alla sua lista clienti.", "dash.weekInitials": "L,M,M,G,V,S,D",
    "plan.dayN": "Giorno {n}", "plan.noDays": "Nessun giorno in questa scheda.", "plan.noExercises": "Nessun esercizio in questo giorno.", "plan.rest": "rec.",
    "myplan.programWeeks": "Programma di {n} settimane", "myplan.todayIs": "Oggi tocca il Giorno {n}.", "myplan.noPlanSub": "Il tuo trainer non ti ha ancora assegnato una scheda.",
    "session.duration": "Durata", "session.inProgress": "In corso", "session.paused": "In pausa", "session.calories": "Calorie", "session.estKcal": "kcal stimate", "session.heart": "Battito", "session.connect": "Collega fascia", "session.na": "non disponibile", "session.exercises": "Esercizi", "session.pause": "Pausa", "session.resume": "Riprendi", "session.finish": "Fine", "session.confirmEnd": "Terminare l'allenamento?", "session.yesEnd": "Sì, termina", "session.saving": "Salvataggio...", "session.workout": "Allenamento",
    "prog.title": "Progressi", "prog.medalsCount": "{a}/{b} medaglie", "prog.day": "Giorno", "prog.week": "Settimana", "prog.rings": "Anelli di attività", "prog.move": "Movimento", "prog.exercise": "Esercizio", "prog.workouts": "Allenamenti", "prog.short": "allen.", "prog.kcal": "kcal", "prog.minutes": "minuti", "prog.avgBpm": "bpm medio", "prog.chart": "Minuti di allenamento", "prog.weekSessions": "Allenamenti della settimana", "prog.oneSession": "Allenamento", "prog.emptyDay": "Nessun allenamento in questo giorno.", "prog.emptyWeek": "Nessun allenamento in questo periodo.", "prog.all": "Tutte", "prog.cal": "cal",
    "medals.title": "Medagliere", "medals.unlockedOf": "{a} di {b} medaglie sbloccate", "medals.trophies": "traguardi raggiunti", "medals.unlocked": "Sbloccate", "medals.locked": "Da conquistare", "medals.how": "Come si sbloccano",
    "medal.first": "Primo passo", "medal.first.d": "Completa il tuo primo allenamento", "medal.s10": "In moto", "medal.s10.d": "10 allenamenti completati", "medal.s25": "Costante", "medal.s25.d": "25 allenamenti completati", "medal.s50": "Inarrestabile", "medal.s50.d": "50 allenamenti completati", "medal.s100": "Leggenda", "medal.s100.d": "100 allenamenti completati", "medal.week1": "Settimana perfetta", "medal.week1.d": "Allenati {n} volte in una settimana", "medal.week4": "Mese perfetto", "medal.week4.d": "4 settimane perfette", "medal.week12": "Trimestre di ferro", "medal.week12.d": "12 settimane perfette", "medal.streak7": "7 di fila", "medal.streak7.d": "7 giorni consecutivi", "medal.streak30": "30 di fila", "medal.streak30.d": "30 giorni consecutivi",
    "chat.empty": "Nessun messaggio. Scrivi il primo!", "chat.placeholder": "Scrivi un messaggio...",
    "msgs.notLinked": "Non sei ancora collegato a un trainer.", "msgs.yourPT": "Il tuo personal trainer", "msgs.select": "Seleziona un cliente per chattare", "msgs.noClients": "Nessun cliente con cui chattare.",
    "profile.subClient": "Gestisci la tua foto, il tuo nome e i tuoi dati.", "profile.subTrainer": "Gestisci la tua foto e il tuo nome.", "profile.trainingData": "I tuoi dati di allenamento",
    "acct.photo": "Foto profilo", "acct.change": "Cambia foto", "acct.uploading": "Caricamento...", "acct.first": "Nome", "acct.last": "Cognome", "acct.saveName": "Salva nome", "acct.nameOk": "Nome aggiornato.", "acct.nameErr": "Errore nell'aggiornamento del nome.", "acct.photoOk": "Foto profilo aggiornata.", "acct.photoErr": "Errore nel caricamento della foto.", "acct.note": "L'email e la password si gestiscono dall'icona account in basso nel menu.",
    "pf.sex": "Sesso", "pf.man": "Uomo", "pf.woman": "Donna", "pf.data": "I tuoi dati", "pf.age": "Età", "pf.height": "Altezza (cm)", "pf.weight": "Peso (kg)", "pf.daysQ": "Quanti giorni a settimana puoi allenarti?", "pf.daysHint": "Aiuta il trainer a impostare la frequenza giusta.", "pf.goals": "Obiettivi", "pf.goalsHint": "Puoi sceglierne più di uno.", "pf.notes": "Note per il trainer (facoltativo)", "pf.notesPh": "Es. infortuni, preferenze, esperienza pregressa, attrezzatura disponibile...", "pf.saved": "Profilo salvato.", "pf.errSex": "Seleziona il sesso.", "pf.errHW": "Inserisci altezza e peso.", "pf.errGoals": "Scegli almeno un obiettivo.",
    "goal.loss": "Dimagrimento", "goal.mass": "Massa muscolare", "goal.strength": "Forza", "goal.tone": "Tonificazione", "goal.endurance": "Resistenza", "goal.health": "Salute generale",
    "setup.hi": "Ciao {name}!", "setup.sub": "Completa il tuo profilo: servirà al tuo trainer per crearti una scheda su misura.", "setup.submit": "Completa profilo",
    "tr.welcome": "Bentornato", "tr.following": "Stai seguendo {n} clienti.", "tr.startFirst": "Inizia invitando il tuo primo cliente.", "tr.addClient": "Aggiungi cliente", "tr.activeClients": "Clienti attivi", "tr.unread": "Messaggi non letti", "tr.toValidate": "Da validare", "tr.earnings": "Guadagni totali", "tr.yourClients": "I tuoi clienti", "tr.seeAll": "Vedi tutti", "tr.noClients": "Nessun cliente ancora.", "tr.addFirst": "Aggiungi il primo", "tr.recs": "Raccomandazioni da validare", "tr.noRecs": "Nessuna raccomandazione in attesa.", "tr.validate": "Valida",
    "wk.newPlan": "Nuova scheda", "wk.newSub": "Imposta i parametri e lascia che l'AI crei la scheda, oppure costruiscila a mano.", "wk.type": "Tipo di allenamento", "wk.freq": "Quante volte a settimana", "wk.clientData": "Dati fisici del cliente", "wk.level": "Livello", "wk.goalsNotes": "Obiettivi e note (facoltativo)", "wk.genAI": "Genera scheda con l'AI", "wk.generating": "Generazione in corso...", "wk.manual": "Crea manualmente", "wk.create": "Crea scheda", "wk.created": "{n} schede create", "wk.none": "Nessuna scheda ancora", "wk.noneSub": "Crea la prima scheda o un modello da riutilizzare.", "wk.template": "Modello", "wk.templateNone": "Modello (nessun cliente)", "wk.activeBadge": "Attiva", "wk.daysN": "{n} giorni", "wk.exercisesN": "{n} esercizi", "wk.weeksShort": "{n} sett.", "wk.open": "Apri",
    "wb.assign": "Assegna a", "wb.noClient": "Nessun cliente — salva come modello", "wb.templateHint": "Salva senza cliente per tenere la scheda come modello da riutilizzare.", "wb.name": "Nome scheda", "wb.namePh": "Es. Massa - Fase 1", "wb.startDate": "Data inizio", "wb.duration": "Durata (settimane)", "wb.endPreview": "Fine prevista: {date}", "wb.desc": "Descrizione (facoltativa)", "wb.descPh": "Note generali sulla scheda...", "wb.dayNamePh": "Nome (es. Petto e tricipiti)", "wb.exPh": "Nome esercizio (es. Panca piana)", "wb.sets": "Serie", "wb.reps": "Ripetizioni", "wb.weight": "Peso (kg)", "wb.rest": "Rec. (s)", "wb.addEx": "Aggiungi esercizio", "wb.addDay": "Giorno", "wb.delDay": "Elimina giorno", "wb.save": "Salva scheda", "wb.saveEdits": "Salva modifiche", "wb.editSettings": "Modifica impostazioni",
    "lvl.beginner": "Principiante", "lvl.intermediate": "Intermedio", "lvl.advanced": "Avanzato",
    "tt.mass": "Ipertrofia / Massa", "tt.strength": "Forza", "tt.loss": "Dimagrimento", "tt.endurance": "Resistenza", "tt.tone": "Tonificazione", "tt.functional": "Functional / Full body",
    "soon.title": "In arrivo presto", "soon.sub": "Stiamo lavorando a questa funzionalità. Sarà disponibile in un prossimo aggiornamento.",
    "common.back": "Indietro", "common.cancel": "Annulla", "common.today": "Oggi",
  },
  en: {
    "nav.dashboard": "Dashboard", "nav.clients": "Clients", "nav.workouts": "Plans", "nav.messages": "Messages", "nav.products": "Products", "nav.earnings": "Earnings", "nav.network": "Network / Invites", "nav.profile": "Profile", "nav.myPlan": "My plan", "nav.progress": "Progress", "nav.medals": "Medals", "nav.shop": "Shop", "nav.catalog": "Product Catalog", "nav.users": "Users", "nav.trainerNetwork": "Trainer Network", "nav.sales": "Sales", "nav.settings": "Settings", "nav.account": "Account",
    "role.trainer": "Personal Trainer", "role.client": "Client", "role.admin": "Admin",
    "notif.title": "Notifications", "notif.markRead": "Mark as read", "notif.empty": "No notifications", "notif.newMessage": "New message from {name}",
    "lang.title": "Language",
    "dash.hi": "Hi, {name}", "dash.today": "Today", "dash.dayOf": "Today · Day {n} of {total}", "dash.doneToday": "Done today", "dash.meta": "{n} exercises · ~{min} min", "dash.moreExercises": "+ {n} more exercises", "dash.start": "Start workout", "dash.startAgain": "Train again", "dash.thisWeek": "This week", "dash.progress": "Progress", "dash.workoutsLabel": "Workouts", "dash.kcalBurned": "kcal burned", "dash.activeTime": "active time", "dash.streak": "day streak", "dash.min": "min", "dash.days": "days", "dash.unread": "Unread", "dash.currentWeight": "Current weight", "dash.shopSub": "BYH picks", "dash.yourTrainer": "Your trainer", "dash.writeTrainer": "Message your trainer", "dash.recommended": "Recommended by your trainer", "dash.noPlan": "No active plan", "dash.noPlanSub": "Your trainer will assign you a program soon.", "dash.waiting": "Waiting for your trainer", "dash.waitingSub": "Your profile will be activated when a trainer adds you to their client list.", "dash.weekInitials": "M,T,W,T,F,S,S",
    "plan.dayN": "Day {n}", "plan.noDays": "No days in this plan.", "plan.noExercises": "No exercises on this day.", "plan.rest": "rest",
    "myplan.programWeeks": "{n}-week program", "myplan.todayIs": "Today is Day {n}.", "myplan.noPlanSub": "Your trainer hasn't assigned you a plan yet.",
    "session.duration": "Duration", "session.inProgress": "In progress", "session.paused": "Paused", "session.calories": "Calories", "session.estKcal": "est. kcal", "session.heart": "Heart rate", "session.connect": "Connect strap", "session.na": "not available", "session.exercises": "Exercises", "session.pause": "Pause", "session.resume": "Resume", "session.finish": "End", "session.confirmEnd": "End the workout?", "session.yesEnd": "Yes, end", "session.saving": "Saving...", "session.workout": "Workout",
    "prog.title": "Progress", "prog.medalsCount": "{a}/{b} medals", "prog.day": "Day", "prog.week": "Week", "prog.rings": "Activity rings", "prog.move": "Move", "prog.exercise": "Exercise", "prog.workouts": "Workouts", "prog.short": "wkts", "prog.kcal": "kcal", "prog.minutes": "minutes", "prog.avgBpm": "avg bpm", "prog.chart": "Workout minutes", "prog.weekSessions": "This week's workouts", "prog.oneSession": "Workout", "prog.emptyDay": "No workout on this day.", "prog.emptyWeek": "No workouts in this period.", "prog.all": "All", "prog.cal": "cal",
    "medals.title": "Medals", "medals.unlockedOf": "{a} of {b} medals unlocked", "medals.trophies": "milestones reached", "medals.unlocked": "Unlocked", "medals.locked": "To earn", "medals.how": "How to unlock them",
    "medal.first": "First step", "medal.first.d": "Complete your first workout", "medal.s10": "Rolling", "medal.s10.d": "10 workouts completed", "medal.s25": "Consistent", "medal.s25.d": "25 workouts completed", "medal.s50": "Unstoppable", "medal.s50.d": "50 workouts completed", "medal.s100": "Legend", "medal.s100.d": "100 workouts completed", "medal.week1": "Perfect week", "medal.week1.d": "Train {n} times in one week", "medal.week4": "Perfect month", "medal.week4.d": "4 perfect weeks", "medal.week12": "Iron quarter", "medal.week12.d": "12 perfect weeks", "medal.streak7": "7 in a row", "medal.streak7.d": "7 consecutive days", "medal.streak30": "30 in a row", "medal.streak30.d": "30 consecutive days",
    "chat.empty": "No messages yet. Write the first one!", "chat.placeholder": "Write a message...",
    "msgs.notLinked": "You're not linked to a trainer yet.", "msgs.yourPT": "Your personal trainer", "msgs.select": "Select a client to chat", "msgs.noClients": "No clients to chat with.",
    "profile.subClient": "Manage your photo, name and data.", "profile.subTrainer": "Manage your photo and name.", "profile.trainingData": "Your training data",
    "acct.photo": "Profile photo", "acct.change": "Change photo", "acct.uploading": "Uploading...", "acct.first": "First name", "acct.last": "Last name", "acct.saveName": "Save name", "acct.nameOk": "Name updated.", "acct.nameErr": "Error updating name.", "acct.photoOk": "Profile photo updated.", "acct.photoErr": "Error uploading photo.", "acct.note": "Email and password are managed from the account icon at the bottom of the menu.",
    "pf.sex": "Sex", "pf.man": "Man", "pf.woman": "Woman", "pf.data": "Your data", "pf.age": "Age", "pf.height": "Height (cm)", "pf.weight": "Weight (kg)", "pf.daysQ": "How many days a week can you train?", "pf.daysHint": "Helps your trainer set the right frequency.", "pf.goals": "Goals", "pf.goalsHint": "You can pick more than one.", "pf.notes": "Notes for your trainer (optional)", "pf.notesPh": "E.g. injuries, preferences, past experience, available equipment...", "pf.saved": "Profile saved.", "pf.errSex": "Select your sex.", "pf.errHW": "Enter height and weight.", "pf.errGoals": "Pick at least one goal.",
    "goal.loss": "Weight loss", "goal.mass": "Muscle mass", "goal.strength": "Strength", "goal.tone": "Toning", "goal.endurance": "Endurance", "goal.health": "General health",
    "setup.hi": "Hi {name}!", "setup.sub": "Complete your profile: your trainer will use it to build your custom plan.", "setup.submit": "Complete profile",
    "tr.welcome": "Welcome back", "tr.following": "You're coaching {n} clients.", "tr.startFirst": "Start by inviting your first client.", "tr.addClient": "Add client", "tr.activeClients": "Active clients", "tr.unread": "Unread messages", "tr.toValidate": "To validate", "tr.earnings": "Total earnings", "tr.yourClients": "Your clients", "tr.seeAll": "See all", "tr.noClients": "No clients yet.", "tr.addFirst": "Add the first", "tr.recs": "Recommendations to validate", "tr.noRecs": "No pending recommendations.", "tr.validate": "Validate",
    "wk.newPlan": "New plan", "wk.newSub": "Set the parameters and let AI build the plan, or create it manually.", "wk.type": "Training type", "wk.freq": "Times per week", "wk.clientData": "Client's physical data", "wk.level": "Level", "wk.goalsNotes": "Goals and notes (optional)", "wk.genAI": "Generate plan with AI", "wk.generating": "Generating...", "wk.manual": "Create manually", "wk.create": "Create plan", "wk.created": "{n} plans created", "wk.none": "No plans yet", "wk.noneSub": "Create your first plan or a reusable template.", "wk.template": "Template", "wk.templateNone": "Template (no client)", "wk.activeBadge": "Active", "wk.daysN": "{n} days", "wk.exercisesN": "{n} exercises", "wk.weeksShort": "{n} wks", "wk.open": "Open",
    "wb.assign": "Assign to", "wb.noClient": "No client — save as template", "wb.templateHint": "Save without a client to keep this plan as a reusable template.", "wb.name": "Plan name", "wb.namePh": "E.g. Mass - Phase 1", "wb.startDate": "Start date", "wb.duration": "Duration (weeks)", "wb.endPreview": "Expected end: {date}", "wb.desc": "Description (optional)", "wb.descPh": "General notes about the plan...", "wb.dayNamePh": "Name (e.g. Chest & triceps)", "wb.exPh": "Exercise name (e.g. Bench press)", "wb.sets": "Sets", "wb.reps": "Reps", "wb.weight": "Weight (kg)", "wb.rest": "Rest (s)", "wb.addEx": "Add exercise", "wb.addDay": "Day", "wb.delDay": "Delete day", "wb.save": "Save plan", "wb.saveEdits": "Save changes", "wb.editSettings": "Edit settings",
    "lvl.beginner": "Beginner", "lvl.intermediate": "Intermediate", "lvl.advanced": "Advanced",
    "tt.mass": "Hypertrophy / Mass", "tt.strength": "Strength", "tt.loss": "Weight loss", "tt.endurance": "Endurance", "tt.tone": "Toning", "tt.functional": "Functional / Full body",
    "soon.title": "Coming soon", "soon.sub": "We're working on this feature. It will be available in an upcoming update.",
    "common.back": "Back", "common.cancel": "Cancel", "common.today": "Today",
  },
  pt: {
    "nav.dashboard": "Painel", "nav.clients": "Clientes", "nav.workouts": "Fichas", "nav.messages": "Mensagens", "nav.products": "Produtos", "nav.earnings": "Ganhos", "nav.network": "Rede / Convites", "nav.profile": "Perfil", "nav.myPlan": "Minha ficha", "nav.progress": "Progresso", "nav.medals": "Medalhas", "nav.shop": "Loja", "nav.catalog": "Catálogo de Produtos", "nav.users": "Usuários", "nav.trainerNetwork": "Rede de Trainers", "nav.sales": "Vendas", "nav.settings": "Configurações", "nav.account": "Conta",
    "role.trainer": "Personal Trainer", "role.client": "Cliente", "role.admin": "Admin",
    "notif.title": "Notificações", "notif.markRead": "Marcar como lidas", "notif.empty": "Nenhuma notificação", "notif.newMessage": "Nova mensagem de {name}",
    "lang.title": "Idioma",
    "dash.hi": "Olá, {name}", "dash.today": "Hoje", "dash.dayOf": "Hoje · Dia {n} de {total}", "dash.doneToday": "Feito hoje", "dash.meta": "{n} exercícios · ~{min} min", "dash.moreExercises": "+ mais {n} exercícios", "dash.start": "Iniciar treino", "dash.startAgain": "Treinar novamente", "dash.thisWeek": "Esta semana", "dash.progress": "Progresso", "dash.workoutsLabel": "Treinos", "dash.kcalBurned": "kcal queimadas", "dash.activeTime": "tempo ativo", "dash.streak": "dias seguidos", "dash.min": "min", "dash.days": "dias", "dash.unread": "Não lidas", "dash.currentWeight": "Peso atual", "dash.shopSub": "Dicas BYH", "dash.yourTrainer": "Seu trainer", "dash.writeTrainer": "Falar com o trainer", "dash.recommended": "Recomendados pelo trainer", "dash.noPlan": "Nenhuma ficha ativa", "dash.noPlanSub": "Seu trainer vai te atribuir um programa em breve.", "dash.waiting": "Aguardando seu trainer", "dash.waitingSub": "Seu perfil será ativado quando um trainer te adicionar à lista de clientes.", "dash.weekInitials": "S,T,Q,Q,S,S,D",
    "plan.dayN": "Dia {n}", "plan.noDays": "Nenhum dia nesta ficha.", "plan.noExercises": "Nenhum exercício neste dia.", "plan.rest": "desc.",
    "myplan.programWeeks": "Programa de {n} semanas", "myplan.todayIs": "Hoje é o Dia {n}.", "myplan.noPlanSub": "Seu trainer ainda não te atribuiu uma ficha.",
    "session.duration": "Duração", "session.inProgress": "Em andamento", "session.paused": "Em pausa", "session.calories": "Calorias", "session.estKcal": "kcal estimadas", "session.heart": "Batimentos", "session.connect": "Conectar cinta", "session.na": "não disponível", "session.exercises": "Exercícios", "session.pause": "Pausa", "session.resume": "Retomar", "session.finish": "Fim", "session.confirmEnd": "Terminar o treino?", "session.yesEnd": "Sim, terminar", "session.saving": "Salvando...", "session.workout": "Treino",
    "prog.title": "Progresso", "prog.medalsCount": "{a}/{b} medalhas", "prog.day": "Dia", "prog.week": "Semana", "prog.rings": "Anéis de atividade", "prog.move": "Movimento", "prog.exercise": "Exercício", "prog.workouts": "Treinos", "prog.short": "treinos", "prog.kcal": "kcal", "prog.minutes": "minutos", "prog.avgBpm": "bpm médio", "prog.chart": "Minutos de treino", "prog.weekSessions": "Treinos da semana", "prog.oneSession": "Treino", "prog.emptyDay": "Nenhum treino neste dia.", "prog.emptyWeek": "Nenhum treino neste período.", "prog.all": "Todas", "prog.cal": "cal",
    "medals.title": "Medalhas", "medals.unlockedOf": "{a} de {b} medalhas desbloqueadas", "medals.trophies": "conquistas alcançadas", "medals.unlocked": "Desbloqueadas", "medals.locked": "A conquistar", "medals.how": "Como desbloquear",
    "medal.first": "Primeiro passo", "medal.first.d": "Complete seu primeiro treino", "medal.s10": "Em movimento", "medal.s10.d": "10 treinos concluídos", "medal.s25": "Constante", "medal.s25.d": "25 treinos concluídos", "medal.s50": "Imparável", "medal.s50.d": "50 treinos concluídos", "medal.s100": "Lenda", "medal.s100.d": "100 treinos concluídos", "medal.week1": "Semana perfeita", "medal.week1.d": "Treine {n} vezes em uma semana", "medal.week4": "Mês perfeito", "medal.week4.d": "4 semanas perfeitas", "medal.week12": "Trimestre de ferro", "medal.week12.d": "12 semanas perfeitas", "medal.streak7": "7 seguidos", "medal.streak7.d": "7 dias consecutivos", "medal.streak30": "30 seguidos", "medal.streak30.d": "30 dias consecutivos",
    "chat.empty": "Nenhuma mensagem. Escreva a primeira!", "chat.placeholder": "Escreva uma mensagem...",
    "msgs.notLinked": "Você ainda não está vinculado a um trainer.", "msgs.yourPT": "Seu personal trainer", "msgs.select": "Selecione um cliente para conversar", "msgs.noClients": "Nenhum cliente para conversar.",
    "profile.subClient": "Gerencie sua foto, nome e dados.", "profile.subTrainer": "Gerencie sua foto e seu nome.", "profile.trainingData": "Seus dados de treino",
    "acct.photo": "Foto de perfil", "acct.change": "Trocar foto", "acct.uploading": "Enviando...", "acct.first": "Nome", "acct.last": "Sobrenome", "acct.saveName": "Salvar nome", "acct.nameOk": "Nome atualizado.", "acct.nameErr": "Erro ao atualizar o nome.", "acct.photoOk": "Foto de perfil atualizada.", "acct.photoErr": "Erro ao enviar a foto.", "acct.note": "E-mail e senha são gerenciados pelo ícone de conta na parte inferior do menu.",
    "pf.sex": "Sexo", "pf.man": "Homem", "pf.woman": "Mulher", "pf.data": "Seus dados", "pf.age": "Idade", "pf.height": "Altura (cm)", "pf.weight": "Peso (kg)", "pf.daysQ": "Quantos dias por semana você pode treinar?", "pf.daysHint": "Ajuda o trainer a definir a frequência certa.", "pf.goals": "Objetivos", "pf.goalsHint": "Você pode escolher mais de um.", "pf.notes": "Notas para o trainer (opcional)", "pf.notesPh": "Ex. lesões, preferências, experiência anterior, equipamento disponível...", "pf.saved": "Perfil salvo.", "pf.errSex": "Selecione o sexo.", "pf.errHW": "Informe altura e peso.", "pf.errGoals": "Escolha pelo menos um objetivo.",
    "goal.loss": "Emagrecimento", "goal.mass": "Massa muscular", "goal.strength": "Força", "goal.tone": "Tonificação", "goal.endurance": "Resistência", "goal.health": "Saúde geral",
    "setup.hi": "Olá {name}!", "setup.sub": "Complete seu perfil: seu trainer vai usá-lo para criar sua ficha sob medida.", "setup.submit": "Completar perfil",
    "tr.welcome": "Bem-vindo de volta", "tr.following": "Você está acompanhando {n} clientes.", "tr.startFirst": "Comece convidando seu primeiro cliente.", "tr.addClient": "Adicionar cliente", "tr.activeClients": "Clientes ativos", "tr.unread": "Mensagens não lidas", "tr.toValidate": "A validar", "tr.earnings": "Ganhos totais", "tr.yourClients": "Seus clientes", "tr.seeAll": "Ver todos", "tr.noClients": "Nenhum cliente ainda.", "tr.addFirst": "Adicionar o primeiro", "tr.recs": "Recomendações a validar", "tr.noRecs": "Nenhuma recomendação pendente.", "tr.validate": "Validar",
    "wk.newPlan": "Nova ficha", "wk.newSub": "Defina os parâmetros e deixe a IA criar a ficha, ou monte manualmente.", "wk.type": "Tipo de treino", "wk.freq": "Quantas vezes por semana", "wk.clientData": "Dados físicos do cliente", "wk.level": "Nível", "wk.goalsNotes": "Objetivos e notas (opcional)", "wk.genAI": "Gerar ficha com IA", "wk.generating": "Gerando...", "wk.manual": "Criar manualmente", "wk.create": "Criar ficha", "wk.created": "{n} fichas criadas", "wk.none": "Nenhuma ficha ainda", "wk.noneSub": "Crie a primeira ficha ou um modelo reutilizável.", "wk.template": "Modelo", "wk.templateNone": "Modelo (sem cliente)", "wk.activeBadge": "Ativa", "wk.daysN": "{n} dias", "wk.exercisesN": "{n} exercícios", "wk.weeksShort": "{n} sem.", "wk.open": "Abrir",
    "wb.assign": "Atribuir a", "wb.noClient": "Sem cliente — salvar como modelo", "wb.templateHint": "Salve sem cliente para manter a ficha como modelo reutilizável.", "wb.name": "Nome da ficha", "wb.namePh": "Ex. Massa - Fase 1", "wb.startDate": "Data de início", "wb.duration": "Duração (semanas)", "wb.endPreview": "Fim previsto: {date}", "wb.desc": "Descrição (opcional)", "wb.descPh": "Notas gerais sobre a ficha...", "wb.dayNamePh": "Nome (ex. Peito e tríceps)", "wb.exPh": "Nome do exercício (ex. Supino reto)", "wb.sets": "Séries", "wb.reps": "Repetições", "wb.weight": "Peso (kg)", "wb.rest": "Desc. (s)", "wb.addEx": "Adicionar exercício", "wb.addDay": "Dia", "wb.delDay": "Excluir dia", "wb.save": "Salvar ficha", "wb.saveEdits": "Salvar alterações", "wb.editSettings": "Editar configurações",
    "lvl.beginner": "Iniciante", "lvl.intermediate": "Intermediário", "lvl.advanced": "Avançado",
    "tt.mass": "Hipertrofia / Massa", "tt.strength": "Força", "tt.loss": "Emagrecimento", "tt.endurance": "Resistência", "tt.tone": "Tonificação", "tt.functional": "Funcional / Full body",
    "soon.title": "Em breve", "soon.sub": "Estamos trabalhando nesta funcionalidade. Estará disponível em uma próxima atualização.",
    "common.back": "Voltar", "common.cancel": "Cancelar", "common.today": "Hoje",
  },
  es: {
    "nav.dashboard": "Panel", "nav.clients": "Clientes", "nav.workouts": "Rutinas", "nav.messages": "Mensajes", "nav.products": "Productos", "nav.earnings": "Ganancias", "nav.network": "Red / Invitaciones", "nav.profile": "Perfil", "nav.myPlan": "Mi rutina", "nav.progress": "Progreso", "nav.medals": "Medallas", "nav.shop": "Tienda", "nav.catalog": "Catálogo de Productos", "nav.users": "Usuarios", "nav.trainerNetwork": "Red de Trainers", "nav.sales": "Ventas", "nav.settings": "Ajustes", "nav.account": "Cuenta",
    "role.trainer": "Personal Trainer", "role.client": "Cliente", "role.admin": "Admin",
    "notif.title": "Notificaciones", "notif.markRead": "Marcar como leídas", "notif.empty": "Sin notificaciones", "notif.newMessage": "Nuevo mensaje de {name}",
    "lang.title": "Idioma",
    "dash.hi": "Hola, {name}", "dash.today": "Hoy", "dash.dayOf": "Hoy · Día {n} de {total}", "dash.doneToday": "Hecho hoy", "dash.meta": "{n} ejercicios · ~{min} min", "dash.moreExercises": "+ otros {n} ejercicios", "dash.start": "Empezar entrenamiento", "dash.startAgain": "Entrenar de nuevo", "dash.thisWeek": "Esta semana", "dash.progress": "Progreso", "dash.workoutsLabel": "Entrenamientos", "dash.kcalBurned": "kcal quemadas", "dash.activeTime": "tiempo activo", "dash.streak": "días seguidos", "dash.min": "min", "dash.days": "días", "dash.unread": "Sin leer", "dash.currentWeight": "Peso actual", "dash.shopSub": "Consejos BYH", "dash.yourTrainer": "Tu trainer", "dash.writeTrainer": "Escribe a tu trainer", "dash.recommended": "Recomendados por tu trainer", "dash.noPlan": "Sin rutina activa", "dash.noPlanSub": "Tu trainer te asignará un programa pronto.", "dash.waiting": "Esperando a tu trainer", "dash.waitingSub": "Tu perfil se activará cuando un trainer te añada a su lista de clientes.", "dash.weekInitials": "L,M,X,J,V,S,D",
    "plan.dayN": "Día {n}", "plan.noDays": "No hay días en esta rutina.", "plan.noExercises": "No hay ejercicios en este día.", "plan.rest": "desc.",
    "myplan.programWeeks": "Programa de {n} semanas", "myplan.todayIs": "Hoy toca el Día {n}.", "myplan.noPlanSub": "Tu trainer aún no te ha asignado una rutina.",
    "session.duration": "Duración", "session.inProgress": "En curso", "session.paused": "En pausa", "session.calories": "Calorías", "session.estKcal": "kcal estimadas", "session.heart": "Pulsaciones", "session.connect": "Conectar banda", "session.na": "no disponible", "session.exercises": "Ejercicios", "session.pause": "Pausa", "session.resume": "Reanudar", "session.finish": "Fin", "session.confirmEnd": "¿Terminar el entrenamiento?", "session.yesEnd": "Sí, terminar", "session.saving": "Guardando...", "session.workout": "Entrenamiento",
    "prog.title": "Progreso", "prog.medalsCount": "{a}/{b} medallas", "prog.day": "Día", "prog.week": "Semana", "prog.rings": "Anillos de actividad", "prog.move": "Movimiento", "prog.exercise": "Ejercicio", "prog.workouts": "Entrenamientos", "prog.short": "entren.", "prog.kcal": "kcal", "prog.minutes": "minutos", "prog.avgBpm": "ppm medio", "prog.chart": "Minutos de entrenamiento", "prog.weekSessions": "Entrenamientos de la semana", "prog.oneSession": "Entrenamiento", "prog.emptyDay": "Sin entrenamiento este día.", "prog.emptyWeek": "Sin entrenamientos en este período.", "prog.all": "Todas", "prog.cal": "cal",
    "medals.title": "Medallas", "medals.unlockedOf": "{a} de {b} medallas desbloqueadas", "medals.trophies": "logros alcanzados", "medals.unlocked": "Desbloqueadas", "medals.locked": "Por conseguir", "medals.how": "Cómo se desbloquean",
    "medal.first": "Primer paso", "medal.first.d": "Completa tu primer entrenamiento", "medal.s10": "En marcha", "medal.s10.d": "10 entrenamientos completados", "medal.s25": "Constante", "medal.s25.d": "25 entrenamientos completados", "medal.s50": "Imparable", "medal.s50.d": "50 entrenamientos completados", "medal.s100": "Leyenda", "medal.s100.d": "100 entrenamientos completados", "medal.week1": "Semana perfecta", "medal.week1.d": "Entrena {n} veces en una semana", "medal.week4": "Mes perfecto", "medal.week4.d": "4 semanas perfectas", "medal.week12": "Trimestre de hierro", "medal.week12.d": "12 semanas perfectas", "medal.streak7": "7 seguidos", "medal.streak7.d": "7 días consecutivos", "medal.streak30": "30 seguidos", "medal.streak30.d": "30 días consecutivos",
    "chat.empty": "Sin mensajes. ¡Escribe el primero!", "chat.placeholder": "Escribe un mensaje...",
    "msgs.notLinked": "Aún no estás vinculado a un trainer.", "msgs.yourPT": "Tu personal trainer", "msgs.select": "Selecciona un cliente para chatear", "msgs.noClients": "No hay clientes con quienes chatear.",
    "profile.subClient": "Gestiona tu foto, tu nombre y tus datos.", "profile.subTrainer": "Gestiona tu foto y tu nombre.", "profile.trainingData": "Tus datos de entrenamiento",
    "acct.photo": "Foto de perfil", "acct.change": "Cambiar foto", "acct.uploading": "Subiendo...", "acct.first": "Nombre", "acct.last": "Apellido", "acct.saveName": "Guardar nombre", "acct.nameOk": "Nombre actualizado.", "acct.nameErr": "Error al actualizar el nombre.", "acct.photoOk": "Foto de perfil actualizada.", "acct.photoErr": "Error al subir la foto.", "acct.note": "El correo y la contraseña se gestionan desde el icono de cuenta abajo en el menú.",
    "pf.sex": "Sexo", "pf.man": "Hombre", "pf.woman": "Mujer", "pf.data": "Tus datos", "pf.age": "Edad", "pf.height": "Altura (cm)", "pf.weight": "Peso (kg)", "pf.daysQ": "¿Cuántos días a la semana puedes entrenar?", "pf.daysHint": "Ayuda al trainer a fijar la frecuencia adecuada.", "pf.goals": "Objetivos", "pf.goalsHint": "Puedes elegir más de uno.", "pf.notes": "Notas para el trainer (opcional)", "pf.notesPh": "Ej. lesiones, preferencias, experiencia previa, equipamiento disponible...", "pf.saved": "Perfil guardado.", "pf.errSex": "Selecciona el sexo.", "pf.errHW": "Introduce altura y peso.", "pf.errGoals": "Elige al menos un objetivo.",
    "goal.loss": "Pérdida de peso", "goal.mass": "Masa muscular", "goal.strength": "Fuerza", "goal.tone": "Tonificación", "goal.endurance": "Resistencia", "goal.health": "Salud general",
    "setup.hi": "¡Hola {name}!", "setup.sub": "Completa tu perfil: tu trainer lo usará para crearte una rutina a medida.", "setup.submit": "Completar perfil",
    "tr.welcome": "Bienvenido de nuevo", "tr.following": "Estás siguiendo a {n} clientes.", "tr.startFirst": "Empieza invitando a tu primer cliente.", "tr.addClient": "Añadir cliente", "tr.activeClients": "Clientes activos", "tr.unread": "Mensajes sin leer", "tr.toValidate": "Por validar", "tr.earnings": "Ganancias totales", "tr.yourClients": "Tus clientes", "tr.seeAll": "Ver todos", "tr.noClients": "Aún no hay clientes.", "tr.addFirst": "Añadir el primero", "tr.recs": "Recomendaciones por validar", "tr.noRecs": "Sin recomendaciones pendientes.", "tr.validate": "Validar",
    "wk.newPlan": "Nueva rutina", "wk.newSub": "Define los parámetros y deja que la IA cree la rutina, o créala a mano.", "wk.type": "Tipo de entrenamiento", "wk.freq": "Veces por semana", "wk.clientData": "Datos físicos del cliente", "wk.level": "Nivel", "wk.goalsNotes": "Objetivos y notas (opcional)", "wk.genAI": "Generar rutina con IA", "wk.generating": "Generando...", "wk.manual": "Crear manualmente", "wk.create": "Crear rutina", "wk.created": "{n} rutinas creadas", "wk.none": "Aún no hay rutinas", "wk.noneSub": "Crea la primera rutina o una plantilla reutilizable.", "wk.template": "Plantilla", "wk.templateNone": "Plantilla (sin cliente)", "wk.activeBadge": "Activa", "wk.daysN": "{n} días", "wk.exercisesN": "{n} ejercicios", "wk.weeksShort": "{n} sem.", "wk.open": "Abrir",
    "wb.assign": "Asignar a", "wb.noClient": "Sin cliente — guardar como plantilla", "wb.templateHint": "Guarda sin cliente para mantener la rutina como plantilla reutilizable.", "wb.name": "Nombre de la rutina", "wb.namePh": "Ej. Masa - Fase 1", "wb.startDate": "Fecha de inicio", "wb.duration": "Duración (semanas)", "wb.endPreview": "Fin previsto: {date}", "wb.desc": "Descripción (opcional)", "wb.descPh": "Notas generales sobre la rutina...", "wb.dayNamePh": "Nombre (ej. Pecho y tríceps)", "wb.exPh": "Nombre del ejercicio (ej. Press banca)", "wb.sets": "Series", "wb.reps": "Repeticiones", "wb.weight": "Peso (kg)", "wb.rest": "Desc. (s)", "wb.addEx": "Añadir ejercicio", "wb.addDay": "Día", "wb.delDay": "Eliminar día", "wb.save": "Guardar rutina", "wb.saveEdits": "Guardar cambios", "wb.editSettings": "Editar ajustes",
    "lvl.beginner": "Principiante", "lvl.intermediate": "Intermedio", "lvl.advanced": "Avanzado",
    "tt.mass": "Hipertrofia / Masa", "tt.strength": "Fuerza", "tt.loss": "Pérdida de peso", "tt.endurance": "Resistencia", "tt.tone": "Tonificación", "tt.functional": "Funcional / Full body",
    "soon.title": "Próximamente", "soon.sub": "Estamos trabajando en esta función. Estará disponible en una próxima actualización.",
    "common.back": "Atrás", "common.cancel": "Cancelar", "common.today": "Hoy",
  },
};

export function translate(
  locale: Locale,
  key: string,
  vars?: Record<string, string | number>
): string {
  let s = dict[locale]?.[key] ?? dict[DEFAULT_LOCALE][key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) s = s.replaceAll(`{${k}}`, String(v));
  }
  return s;
}

export const DATE_LOCALE: Record<Locale, string> = {
  it: "it-IT",
  en: "en-GB",
  pt: "pt-PT",
  es: "es-ES",
};
